# Julien Wollbrett Feb 9, 2021
## This script calculate fpkm from calls files generated by BgeeCall
## It is a really simple that only add one "fpkm" column to each calls file.
## It does not create a new file but simply update existing ones (if they do not already have a "fpkm" column)

## Usage as for Bgee15:
## R CMD BATCH --no-save --no-restore '--args all_results_dir=$(RNASEQ_CLUSTER_BGEECALL_CALLS) calls_file_name=$(ABUNDANCEFILE)' calculate_fpkm.R calculate_fpkm.Rout
## all_results_dir          - path to the directory containing BgeeCall results for all libraries
## calls_file_name          - name of the file containing calls/length/count/tpms

## Session info
print(sessionInfo())

## reading in arguments provided in command line
cmd_args = commandArgs(TRUE);
print(cmd_args)
if( length(cmd_args) == 0 ){ stop("no arguments provided\n") } else {
  for( i in 1:length(cmd_args) ){
    eval(parse(text=cmd_args[i]))
  }
}

## checking if all necessary arguments were passed in command line
command_arg <- c("all_results_dir", "calls_file_name")
for( c_arg in command_arg ){
  if( !exists(c_arg) ){
    stop( paste(c_arg,"command line argument not provided\n") )
  }
}

# escape "+" character
calls_file_name <- gsub(pattern = "\\+", replacement = "\\\\+", x = calls_file_name)
##

######################### FUNCTION ###########################
estCount_to_fpkm <- function(est_count, effec_length){
  N <- sum(est_count)
  return( exp(log(est_count) + log(1e9) - log(effec_length) - log(N)) )
}
##############################################################
# detect all calls files generated by BgeeCall
calls_files <- list.files(path = all_results_dir, pattern = calls_file_name, 
  recursive = TRUE, full.names = TRUE)
for(i in seq_len(length(calls_files))) {
  calls <- read.table(calls_files[i], header = TRUE, sep = "\t")
  if( is.null(calls$fpkm) ) {
    calls$fpkm <- estCount_to_fpkm(calls$counts, calls$length)
    write.table(x = calls, file = calls_files[i], quote = FALSE, row.names = FALSE, col.names = TRUE,
      sep = "\t")
  }
}


