-- TODO enable multispecies groups when necessary
-- TODO fix insertion of download files

-- query to get the single species data groups for easier generation of this file:
SELECT speciesDisplayOrder,
        IF(speciesCommonName IS NOT NULL AND speciesCommonName != '',
           speciesCommonName, CONCAT(genus, ' ', species)),
        speciesDisplayOrder
FROM species ORDER BY speciesDisplayOrder;

-- query to get member of a given taxon, to help build the multi-species groups
SELECT t3.* from taxon as t1 inner join taxon as t2 
    ON t2.taxonLeftBound >= t1.taxonLeftBound
    AND t2.taxonRightBound <= t1.taxonRightBound
INNER JOIN species AS t3 on t3.taxonId = t2.taxonId
WHERE t1.taxonId = 1437010;

DELETE FROM downloadFile;
DELETE from speciesDataGroup;


INSERT INTO speciesDataGroup (speciesDataGroupId, speciesDataGroupName, speciesDataGroupDescription,
speciesDataGroupOrder) VALUES
-- single-species data groups
(1, 'human', NULL, 1),
(2, 'mouse', NULL, 2),
(3, 'zebrafish', NULL, 3),
(4, 'fruit fly', NULL, 4),
(5, 'nematode', NULL, 5),
(6, 'chimpanzee', NULL, 6),
(7, 'bonobo', NULL, 7),
(8, 'gorilla', NULL, 8),
(9, 'macaque', NULL, 9),
(10, 'rat', NULL, 10),
(11, 'cattle', NULL, 11),
(12, 'pig', NULL, 12),
(13, 'horse', NULL, 13),
(14, 'rabbit', NULL, 14),
(15, 'dog', NULL, 15),
(16, 'cat', NULL, 16),
(17, 'guinea pig', NULL, 17),
(18, 'hedgehog', NULL, 18),
(19, 'opossum', NULL, 19),
(20, 'platypus', NULL, 20),
(21, 'chicken', NULL, 21),
(22, 'green anole', NULL, 22),
(23, 'western clawed frog', NULL, 23),
(24, 'Drosophila ananassae', NULL, 24),
(25, 'Drosophila mojavensis', NULL, 25),
(26, 'Drosophila pseudoobscura', NULL, 26),
(27, 'Drosophila simulans', NULL, 27),
(28, 'Drosophila virilis', NULL, 28),
(29, 'Drosophila yakuba', NULL, 29)

-- ,
-- multi-species data group
-- (30, 'human/mouse', NULL, 30),
-- (31, 'Primates', NULL, 31),
-- (32, 'Rodentia', NULL, 32),
-- (33, 'Theria', NULL, 33),
-- (34, 'Mammalia', NULL, 34),
-- (35, 'Amniota', NULL, 35),
-- (36, 'Tetrapoda', NULL, 36),
-- (37, 'Teleostomi', NULL, 37),
--
-- (39, 'Drosophila (genus)', NULL, 38),
-- worm + drosophila
-- (40, 'Ecdysozoa', NULL, 39),
--
-- hedgehog, dog, cat, horse, pig, cattle
-- (38, 'Laurasiatheria', NULL, 40),
-- (41, 'Livestock', NULL, 41),
-- (42, 'Domestic animals', NULL, 42)
;


INSERT INTO speciesToDataGroup (speciesDataGroupId, speciesId) VALUES 
-- single-species data groups
(1, 9606),
(2, 10090),
(3, 7955),
(4, 7227),
(5, 6239),
(6, 9598),
(7, 9597),
(8, 9593),
(9, 9544),
(10, 10116),
(11, 9913),
(12, 9823),
(13, 9796),
(14, 9986),
(15, 9615),
(16, 9685),
(17, 10141),
(18, 9365),
(19, 13616),
(20, 9258),
(21, 9031),
(22, 28377),
(23, 8364),
(24, 7217),
(25, 7230),
(26, 7237),
(27, 7240),
(28, 7244),
(29, 7245)
-- ,
-- multi-species data groups
-- (30, 9606),
-- (30, 10090),
--
-- (31, 9606),
-- (31, 9598),
-- (31, 9597),
-- (31, 9593),
-- (31, 9544),
--
-- (32, 10090),
-- (32, 10116),
-- (32, 10141),
--
-- (33, 9606),
-- (33, 10090),
-- (33, 9598),
-- (33, 9597),
-- (33, 9593),
-- (33, 9544),
-- (33, 10116),
-- (33, 9913),
-- (33, 9823),
-- (33, 9796),
-- (33, 9986),
-- (33, 9615),
-- (33, 9685),
-- (33, 10141),
-- (33, 9365),
-- (33, 13616),
--
-- (34, 9606),
-- (34, 10090),
-- (34, 9598),
-- (34, 9597),
-- (34, 9593),
-- (34, 9544),
-- (34, 10116),
-- (34, 9913),
-- (34, 9823),
-- (34, 9796),
-- (34, 9986),
-- (34, 9615),
-- (34, 9685),
-- (34, 10141),
-- (34, 9365),
-- (34, 13616),
-- (34, 9258),
--
-- (35, 9606),
-- (35, 10090),
-- (35, 9598),
-- (35, 9597),
-- (35, 9593),
-- (35, 9544),
-- (35, 10116),
-- (35, 9913),
-- (35, 9823),
-- (35, 9796),
-- (35, 9986),
-- (35, 9615),
-- (35, 9685),
-- (35, 10141),
-- (35, 9365),
-- (35, 13616),
-- (35, 9258),
-- (35, 9031),
-- (35, 28377),
--
-- (36, 9606),
-- (36, 10090),
-- (36, 9598),
-- (36, 9597),
-- (36, 9593),
-- (36, 9544),
-- (36, 10116),
-- (36, 9913),
-- (36, 9823),
-- (36, 9796),
-- (36, 9986),
-- (36, 9615),
-- (36, 9685),
-- (36, 10141),
-- (36, 9365),
-- (36, 13616),
-- (36, 9258),
-- (36, 9031),
-- (36, 28377),
-- (36, 8364),
--
-- (37, 9606),
-- (37, 10090),
-- (37, 9598),
-- (37, 9597),
-- (37, 9593),
-- (37, 9544),
-- (37, 10116),
-- (37, 9913),
-- (37, 9823),
-- (37, 9796),
-- (37, 9986),
-- (37, 9615),
-- (37, 9685),
-- (37, 10141),
-- (37, 9365),
-- (37, 13616),
-- (37, 9258),
-- (37, 9031),
-- (37, 28377),
-- (37, 8364),
-- (37, 7955),
--
-- (38, 9913),
-- (38, 9823),
-- (38, 9796),
-- (38, 9615),
-- (38, 9685),
-- (38, 9365),
--
-- (39, 7227),
-- (39, 7217),
-- (39, 7230),
-- (39, 7237),
-- (39, 7240),
-- (39, 7244),
-- (39, 7245),
--
-- (40, 7227),
-- (40, 7217),
-- (40, 7230),
-- (40, 7237),
-- (40, 7240),
-- (40, 7244),
-- (40, 7245),
-- (40, 6239),
--
-- (41, 9823),
-- (41, 9913),
--
-- (42, 9031),
-- (42, 9615),
-- (42, 9685),
-- (42, 9796),
-- (42, 9823),
-- (42, 9913),
-- (42, 9986),
-- (42, 10141)
;

INSERT INTO downloadFile (downloadFileId, downloadFileRelativePath, downloadFileName, downloadFileCategory, speciesDataGroupId, downloadFileSize, downloadFileConditionParameters)
VALUES (1, "calls/expr_calls/Anolis_carolinensis_expr_advanced.tsv.gz", "Anolis_carolinensis_expr_advanced.tsv.gz", "expr_complete", 22, 2201338, "anatomicalEntity"),
(2, "calls/expr_calls/Anolis_carolinensis_expr_advanced_development.tsv.gz", "Anolis_carolinensis_expr_advanced_development.tsv.gz", "expr_complete", 22, 2827012, "anatomicalEntity,developmentalStage"),
(3, "calls/expr_calls/Anolis_carolinensis_expr_simple.tsv.gz", "Anolis_carolinensis_expr_simple.tsv.gz", "expr_simple", 22, 1827288, "anatomicalEntity"),
(4, "calls/expr_calls/Anolis_carolinensis_expr_simple_development.tsv.gz", "Anolis_carolinensis_expr_simple_development.tsv.gz", "expr_simple", 22, 2436754, "anatomicalEntity,developmentalStage"),
(5, "calls/expr_calls/Bos_taurus_expr_advanced.tsv.gz", "Bos_taurus_expr_advanced.tsv.gz", "expr_complete", 11, 19378996, "anatomicalEntity"),
(6, "calls/expr_calls/Bos_taurus_expr_advanced_development.tsv.gz", "Bos_taurus_expr_advanced_development.tsv.gz", "expr_complete", 11, 25222389, "anatomicalEntity,developmentalStage"),
(7, "calls/expr_calls/Bos_taurus_expr_simple.tsv.gz", "Bos_taurus_expr_simple.tsv.gz", "expr_simple", 11, 15491056, "anatomicalEntity"),
(8, "calls/expr_calls/Bos_taurus_expr_simple_development.tsv.gz", "Bos_taurus_expr_simple_development.tsv.gz", "expr_simple", 11, 21835947, "anatomicalEntity,developmentalStage"),
(9, "calls/expr_calls/Caenorhabditis_elegans_expr_advanced.tsv.gz", "Caenorhabditis_elegans_expr_advanced.tsv.gz", "expr_complete", 5, 1296111, "anatomicalEntity"),
(10, "calls/expr_calls/Caenorhabditis_elegans_expr_advanced_development.tsv.gz", "Caenorhabditis_elegans_expr_advanced_development.tsv.gz", "expr_complete", 5, 7329354, "anatomicalEntity,developmentalStage"),
(11, "calls/expr_calls/Caenorhabditis_elegans_expr_simple.tsv.gz", "Caenorhabditis_elegans_expr_simple.tsv.gz", "expr_simple", 5, 994232, "anatomicalEntity"),
(12, "calls/expr_calls/Caenorhabditis_elegans_expr_simple_development.tsv.gz", "Caenorhabditis_elegans_expr_simple_development.tsv.gz", "expr_simple", 5, 5986930, "anatomicalEntity,developmentalStage"),
(13, "calls/expr_calls/Canis_lupus_familiaris_expr_advanced.tsv.gz", "Canis_lupus_familiaris_expr_advanced.tsv.gz", "expr_complete", 15, 10202675, "anatomicalEntity"),
(14, "calls/expr_calls/Canis_lupus_familiaris_expr_advanced_development.tsv.gz", "Canis_lupus_familiaris_expr_advanced_development.tsv.gz", "expr_complete", 15, 14849306, "anatomicalEntity,developmentalStage"),
(15, "calls/expr_calls/Canis_lupus_familiaris_expr_simple.tsv.gz", "Canis_lupus_familiaris_expr_simple.tsv.gz", "expr_simple", 15, 8222256, "anatomicalEntity"),
(16, "calls/expr_calls/Canis_lupus_familiaris_expr_simple_development.tsv.gz", "Canis_lupus_familiaris_expr_simple_development.tsv.gz", "expr_simple", 15, 12262543, "anatomicalEntity,developmentalStage"),
(17, "calls/expr_calls/Cavia_porcellus_expr_advanced.tsv.gz", "Cavia_porcellus_expr_advanced.tsv.gz", "expr_complete", 17, 2402558, "anatomicalEntity"),
(18, "calls/expr_calls/Cavia_porcellus_expr_advanced_development.tsv.gz", "Cavia_porcellus_expr_advanced_development.tsv.gz", "expr_complete", 17, 2592421, "anatomicalEntity,developmentalStage"),
(19, "calls/expr_calls/Cavia_porcellus_expr_simple.tsv.gz", "Cavia_porcellus_expr_simple.tsv.gz", "expr_simple", 17, 2183364, "anatomicalEntity"),
(20, "calls/expr_calls/Cavia_porcellus_expr_simple_development.tsv.gz", "Cavia_porcellus_expr_simple_development.tsv.gz", "expr_simple", 17, 12262543, "anatomicalEntity,developmentalStage"),
(21, "calls/expr_calls/Danio_rerio_expr_advanced.tsv.gz", "Danio_rerio_expr_advanced.tsv.gz", "expr_complete", 3, 8859724, "anatomicalEntity"),
(22, "calls/expr_calls/Danio_rerio_expr_advanced_development.tsv.gz", "Danio_rerio_expr_advanced_development.tsv.gz", "expr_complete", 3, 17064556, "anatomicalEntity,developmentalStage"),
(23, "calls/expr_calls/Danio_rerio_expr_simple.tsv.gz", "Danio_rerio_expr_simple.tsv.gz", "expr_simple", 3, 6560839, "anatomicalEntity"),
(24, "calls/expr_calls/Danio_rerio_expr_simple_development.tsv.gz", "Danio_rerio_expr_simple_development.tsv.gz", "expr_simple", 3, 13022659, "anatomicalEntity,developmentalStage"),
(25, "calls/expr_calls/Drosophila_ananassae_expr_advanced.tsv.gz", "Drosophila_ananassae_expr_advanced.tsv.gz", "expr_complete", 24, 120547, "anatomicalEntity"),
(26, "calls/expr_calls/Drosophila_ananassae_expr_advanced_development.tsv.gz", "Drosophila_ananassae_expr_advanced_development.tsv.gz", "expr_complete", 24, 120568, "anatomicalEntity,developmentalStage"),
(27, "calls/expr_calls/Drosophila_ananassae_expr_simple.tsv.gz", "Drosophila_ananassae_expr_simple.tsv.gz", "expr_simple", 24, 112043, "anatomicalEntity"),
(28, "calls/expr_calls/Drosophila_ananassae_expr_simple_development.tsv.gz", "Drosophila_ananassae_expr_simple_development.tsv.gz", "expr_simple", 24, 116012, "anatomicalEntity,developmentalStage"),
(29, "calls/expr_calls/Drosophila_melanogaster_expr_advanced.tsv.gz", "Drosophila_melanogaster_expr_advanced.tsv.gz", "expr_complete", 4, 6449175, "anatomicalEntity"),
(30, "calls/expr_calls/Drosophila_melanogaster_expr_advanced_development.tsv.gz", "Drosophila_melanogaster_expr_advanced_development.tsv.gz", "expr_complete", 4, 18338331, "anatomicalEntity,developmentalStage"),
(31, "calls/expr_calls/Drosophila_melanogaster_expr_simple.tsv.gz", "Drosophila_melanogaster_expr_simple.tsv.gz", "expr_simple", 4, 4414747, "anatomicalEntity"),
(32, "calls/expr_calls/Drosophila_melanogaster_expr_simple_development.tsv.gz", "Drosophila_melanogaster_expr_simple_development.tsv.gz", "expr_simple", 4, 13177369, "anatomicalEntity,developmentalStage"),
(33, "calls/expr_calls/Drosophila_mojavensis_expr_advanced.tsv.gz", "Drosophila_mojavensis_expr_advanced.tsv.gz", "expr_complete", 25, 211593, "anatomicalEntity"),
(34, "calls/expr_calls/Drosophila_mojavensis_expr_advanced_development.tsv.gz", "Drosophila_mojavensis_expr_advanced_development.tsv.gz", "expr_complete", 25, 212762, "anatomicalEntity,developmentalStage"),
(35, "calls/expr_calls/Drosophila_mojavensis_expr_simple.tsv.gz", "Drosophila_mojavensis_expr_simple.tsv.gz", "expr_simple", 25, 192298, "anatomicalEntity"),
(36, "calls/expr_calls/Drosophila_mojavensis_expr_simple_development.tsv.gz", "Drosophila_mojavensis_expr_simple_development.tsv.gz", "expr_simple", 25, 207129, "anatomicalEntity,developmentalStage"),
(37, "calls/expr_calls/Drosophila_pseudoobscura_expr_advanced.tsv.gz", "Drosophila_pseudoobscura_expr_advanced.tsv.gz", "expr_complete", 26, 429799, "anatomicalEntity"),
(38, "calls/expr_calls/Drosophila_pseudoobscura_expr_advanced_development.tsv.gz", "Drosophila_pseudoobscura_expr_advanced_development.tsv.gz", "expr_complete", 26, 433236, "anatomicalEntity,developmentalStage"),
(39, "calls/expr_calls/Drosophila_pseudoobscura_expr_simple.tsv.gz", "Drosophila_pseudoobscura_expr_simple.tsv.gz", "expr_simple", 26, 393035, "anatomicalEntity"),
(40, "calls/expr_calls/Drosophila_pseudoobscura_expr_simple_development.tsv.gz", "Drosophila_pseudoobscura_expr_simple_development.tsv.gz", "expr_simple", 26, 413639, "anatomicalEntity,developmentalStage"),
(41, "calls/expr_calls/Drosophila_simulans_expr_advanced.tsv.gz", "Drosophila_simulans_expr_advanced.tsv.gz", "expr_complete", 27, 433110, "anatomicalEntity"),
(42, "calls/expr_calls/Drosophila_simulans_expr_advanced_development.tsv.gz", "Drosophila_simulans_expr_advanced_development.tsv.gz", "expr_complete", 27, 432851, "anatomicalEntity,developmentalStage"),
(43, "calls/expr_calls/Drosophila_simulans_expr_simple.tsv.gz", "Drosophila_simulans_expr_simple.tsv.gz", "expr_simple", 27, 391638, "anatomicalEntity"),
(44, "calls/expr_calls/Drosophila_simulans_expr_simple_development.tsv.gz", "Drosophila_simulans_expr_simple_development.tsv.gz", "expr_simple", 27, 410615, "anatomicalEntity,developmentalStage"),
(45, "calls/expr_calls/Drosophila_virilis_expr_advanced.tsv.gz", "Drosophila_virilis_expr_advanced.tsv.gz", "expr_complete", 28, 118412, "anatomicalEntity"),
(46, "calls/expr_calls/Drosophila_virilis_expr_advanced_development.tsv.gz", "Drosophila_virilis_expr_advanced_development.tsv.gz", "expr_complete", 28, 118349, "anatomicalEntity,developmentalStage"),
(47, "calls/expr_calls/Drosophila_virilis_expr_simple.tsv.gz", "Drosophila_virilis_expr_simple.tsv.gz", "expr_simple", 28, 110152, "anatomicalEntity"),
(48, "calls/expr_calls/Drosophila_virilis_expr_simple_development.tsv.gz", "Drosophila_virilis_expr_simple_development.tsv.gz", "expr_simple", 28, 113905, "anatomicalEntity,developmentalStage"),
(49, "calls/expr_calls/Drosophila_yakuba_expr_advanced.tsv.gz", "Drosophila_yakuba_expr_advanced.tsv.gz", "expr_complete", 29, 132504, "anatomicalEntity"),
(50, "calls/expr_calls/Drosophila_yakuba_expr_advanced_development.tsv.gz", "Drosophila_yakuba_expr_advanced_development.tsv.gz", "expr_complete", 29, 132114, "anatomicalEntity,developmentalStage"),
(51, "calls/expr_calls/Drosophila_yakuba_expr_simple.tsv.gz", "Drosophila_yakuba_expr_simple.tsv.gz", "expr_simple", 29, 123469, "anatomicalEntity"),
(52, "calls/expr_calls/Drosophila_yakuba_expr_simple_development.tsv.gz", "Drosophila_yakuba_expr_simple_development.tsv.gz", "expr_simple", 29, 127639, "anatomicalEntity,developmentalStage"),
(53, "calls/expr_calls/Equus_caballus_expr_advanced.tsv.gz", "Equus_caballus_expr_advanced.tsv.gz", "expr_complete", 13, 4686748, "anatomicalEntity"),
(54, "calls/expr_calls/Equus_caballus_expr_advanced_development.tsv.gz", "Equus_caballus_expr_advanced_development.tsv.gz", "expr_complete", 13, 6193434, "anatomicalEntity,developmentalStage"),
(55, "calls/expr_calls/Equus_caballus_expr_simple.tsv.gz", "Equus_caballus_expr_simple.tsv.gz", "expr_simple", 13, 3772853, "anatomicalEntity"),
(56, "calls/expr_calls/Equus_caballus_expr_simple_development.tsv.gz", "Equus_caballus_expr_simple_development.tsv.gz", "expr_simple", 13, 5178187, "anatomicalEntity,developmentalStage"),
(57, "calls/expr_calls/Erinaceus_europaeus_expr_advanced.tsv.gz", "Erinaceus_europaeus_expr_advanced.tsv.gz", "expr_complete", 18, 383445, "anatomicalEntity"),
(58, "calls/expr_calls/Erinaceus_europaeus_expr_advanced_development.tsv.gz", "Erinaceus_europaeus_expr_advanced_development.tsv.gz", "expr_complete", 18, 384986, "anatomicalEntity,developmentalStage"),
(59, "calls/expr_calls/Erinaceus_europaeus_expr_simple.tsv.gz", "Erinaceus_europaeus_expr_simple.tsv.gz", "expr_simple", 18, 347611, "anatomicalEntity"),
(60, "calls/expr_calls/Erinaceus_europaeus_expr_simple_development.tsv.gz", "Erinaceus_europaeus_expr_simple_development.tsv.gz", "expr_simple", 18, 361669, "anatomicalEntity,developmentalStage"),
(61, "calls/expr_calls/Felis_catus_expr_advanced.tsv.gz", "Felis_catus_expr_advanced.tsv.gz", "expr_complete", 16, 1758282, "anatomicalEntity"),
(62, "calls/expr_calls/Felis_catus_expr_advanced_development.tsv.gz", "Felis_catus_expr_advanced_development.tsv.gz", "expr_complete", 16, 1780776, "anatomicalEntity,developmentalStage"),
(63, "calls/expr_calls/Felis_catus_expr_simple.tsv.gz", "Felis_catus_expr_simple.tsv.gz", "expr_simple", 16, 1494986, "anatomicalEntity"),
(64, "calls/expr_calls/Felis_catus_expr_simple_development.tsv.gz", "Felis_catus_expr_simple_development.tsv.gz", "expr_simple", 16, 1570239, "anatomicalEntity,developmentalStage"),
(65, "calls/expr_calls/Gallus_gallus_expr_advanced.tsv.gz", "Gallus_gallus_expr_advanced.tsv.gz", "expr_complete", 21, 1735685, "anatomicalEntity"),
(66, "calls/expr_calls/Gallus_gallus_expr_advanced_development.tsv.gz", "Gallus_gallus_expr_advanced_development.tsv.gz", "expr_complete", 21, 2334234, "anatomicalEntity,developmentalStage"),
(67, "calls/expr_calls/Gallus_gallus_expr_simple.tsv.gz", "Gallus_gallus_expr_simple.tsv.gz", "expr_simple", 21, 1410578, "anatomicalEntity"),
(68, "calls/expr_calls/Gallus_gallus_expr_simple_development.tsv.gz", "Gallus_gallus_expr_simple_development.tsv.gz", "expr_simple", 21, 2040126, "anatomicalEntity,developmentalStage"),
(69, "calls/expr_calls/Gorilla_gorilla_expr_advanced.tsv.gz", "Gorilla_gorilla_expr_advanced.tsv.gz", "expr_complete", 8, 1484885, "anatomicalEntity"),
(70, "calls/expr_calls/Gorilla_gorilla_expr_advanced_development.tsv.gz", "Gorilla_gorilla_expr_advanced_development.tsv.gz", "expr_complete", 8, 1507501, "anatomicalEntity,developmentalStage"),
(71, "calls/expr_calls/Gorilla_gorilla_expr_simple.tsv.gz", "Gorilla_gorilla_expr_simple.tsv.gz", "expr_simple", 8, 1226589, "anatomicalEntity"),
(72, "calls/expr_calls/Gorilla_gorilla_expr_simple_development.tsv.gz", "Gorilla_gorilla_expr_simple_development.tsv.gz", "expr_simple", 8, 1285485, "anatomicalEntity,developmentalStage"),
(73, "calls/expr_calls/Homo_sapiens_expr_advanced.tsv.gz", "Homo_sapiens_expr_advanced.tsv.gz", "expr_complete", 1, 129654467, "anatomicalEntity"),
(74, "calls/expr_calls/Homo_sapiens_expr_advanced_development.tsv.gz", "Homo_sapiens_expr_advanced_development.tsv.gz", "expr_complete", 1, 427520935, "anatomicalEntity,developmentalStage"),
(75, "calls/expr_calls/Homo_sapiens_expr_simple.tsv.gz", "Homo_sapiens_expr_simple.tsv.gz", "expr_simple", 1, 74008533, "anatomicalEntity"),
(76, "calls/expr_calls/Homo_sapiens_expr_simple_development.tsv.gz", "Homo_sapiens_expr_simple_development.tsv.gz", "expr_simple", 1, 362882740, "anatomicalEntity,developmentalStage"),
(77, "calls/expr_calls/Macaca_mulatta_expr_advanced.tsv.gz", "Macaca_mulatta_expr_advanced.tsv.gz", "expr_complete", 9, 5825880, "anatomicalEntity"),
(78, "calls/expr_calls/Macaca_mulatta_expr_advanced_development.tsv.gz", "Macaca_mulatta_expr_advanced_development.tsv.gz", "expr_complete", 9, 9044654, "anatomicalEntity,developmentalStage"),
(79, "calls/expr_calls/Macaca_mulatta_expr_simple.tsv.gz", "Macaca_mulatta_expr_simple.tsv.gz", "expr_simple", 9, 4485109, "anatomicalEntity"),
(80, "calls/expr_calls/Macaca_mulatta_expr_simple_development.tsv.gz", "Macaca_mulatta_expr_simple_development.tsv.gz", "expr_simple", 9, 7226136, "anatomicalEntity,developmentalStage"),
(81, "calls/expr_calls/Monodelphis_domestica_expr_advanced.tsv.gz", "Monodelphis_domestica_expr_advanced.tsv.gz", "expr_complete", 19, 4040371, "anatomicalEntity"),
(82, "calls/expr_calls/Monodelphis_domestica_expr_advanced_development.tsv.gz", "Monodelphis_domestica_expr_advanced_development.tsv.gz", "expr_complete", 19, 4485109, "anatomicalEntity,developmentalStage"),
(83, "calls/expr_calls/Monodelphis_domestica_expr_simple.tsv.gz", "Monodelphis_domestica_expr_simple.tsv.gz", "expr_simple", 19, 3244267, "anatomicalEntity"),
(84, "calls/expr_calls/Monodelphis_domestica_expr_simple_development.tsv.gz", "Monodelphis_domestica_expr_simple_development.tsv.gz", "expr_simple", 19, 5337807, "anatomicalEntity,developmentalStage"),
(85, "calls/expr_calls/Mus_musculus_expr_advanced.tsv.gz", "Mus_musculus_expr_advanced.tsv.gz", "expr_complete", 2, 115354188, "anatomicalEntity"),
(86, "calls/expr_calls/Mus_musculus_expr_advanced_development.tsv.gz", "Mus_musculus_expr_advanced_development.tsv.gz", "expr_complete", 2, 278889693, "anatomicalEntity,developmentalStage"),
(87, "calls/expr_calls/Mus_musculus_expr_simple.tsv.gz", "Mus_musculus_expr_simple.tsv.gz", "expr_simple", 2, 63447694, "anatomicalEntity"),
(88, "calls/expr_calls/Mus_musculus_expr_simple_development.tsv.gz", "Mus_musculus_expr_simple_development.tsv.gz", "expr_simple", 2, 207645856, "anatomicalEntity,developmentalStage"),
(89, "calls/expr_calls/Ornithorhynchus_anatinus_expr_advanced.tsv.gz", "Ornithorhynchus_anatinus_expr_advanced.tsv.gz", "expr_complete", 20, 1440175, "anatomicalEntity"),
(90, "calls/expr_calls/Ornithorhynchus_anatinus_expr_advanced_development.tsv.gz", "Ornithorhynchus_anatinus_expr_advanced_development.tsv.gz", "expr_complete", 20, 1618586, "anatomicalEntity,developmentalStage"),
(91, "calls/expr_calls/Ornithorhynchus_anatinus_expr_simple.tsv.gz", "Ornithorhynchus_anatinus_expr_simple.tsv.gz", "expr_simple", 20, 1218345, "anatomicalEntity"),
(92, "calls/expr_calls/Ornithorhynchus_anatinus_expr_simple_development.tsv.gz", "Ornithorhynchus_anatinus_expr_simple_development.tsv.gz", "expr_simple", 20, 1441508, "anatomicalEntity,developmentalStage"),
(93, "calls/expr_calls/Oryctolagus_cuniculus_expr_advanced.tsv.gz", "Oryctolagus_cuniculus_expr_advanced.tsv.gz", "expr_complete", 14, 3366825, "anatomicalEntity"),
(94, "calls/expr_calls/Oryctolagus_cuniculus_expr_advanced_development.tsv.gz", "Oryctolagus_cuniculus_expr_advanced_development.tsv.gz", "expr_complete", 14, 4243082, "anatomicalEntity,developmentalStage"),
(95, "calls/expr_calls/Oryctolagus_cuniculus_expr_simple.tsv.gz", "Oryctolagus_cuniculus_expr_simple.tsv.gz", "expr_simple", 14, 2690766, "anatomicalEntity"),
(96, "calls/expr_calls/Oryctolagus_cuniculus_expr_simple_development.tsv.gz", "Oryctolagus_cuniculus_expr_simple_development.tsv.gz", "expr_simple", 14, 3501132, "anatomicalEntity,developmentalStage"),
(97, "calls/expr_calls/Pan_paniscus_expr_advanced.tsv.gz", "Pan_paniscus_expr_advanced.tsv.gz", "expr_complete", 7, 1090386, "anatomicalEntity"),
(98, "calls/expr_calls/Pan_paniscus_expr_advanced_development.tsv.gz", "Pan_paniscus_expr_advanced_development.tsv.gz", "expr_complete", 7, 1832458, "anatomicalEntity,developmentalStage"),
(99, "calls/expr_calls/Pan_paniscus_expr_simple.tsv.gz", "Pan_paniscus_expr_simple.tsv.gz", "expr_simple", 7, 968484, "anatomicalEntity"),
(100, "calls/expr_calls/Pan_paniscus_expr_simple_development.tsv.gz", "Pan_paniscus_expr_simple_development.tsv.gz", "expr_simple", 7, 1656851, "anatomicalEntity,developmentalStage"),
(101, "calls/expr_calls/Pan_troglodytes_expr_advanced.tsv.gz", "Pan_troglodytes_expr_advanced.tsv.gz", "expr_complete", 6, 5126693, "anatomicalEntity"),
(102, "calls/expr_calls/Pan_troglodytes_expr_advanced_development.tsv.gz", "Pan_troglodytes_expr_advanced_development.tsv.gz", "expr_complete", 6, 9359770, "anatomicalEntity,developmentalStage"),
(103, "calls/expr_calls/Pan_troglodytes_expr_simple.tsv.gz", "Pan_troglodytes_expr_simple.tsv.gz", "expr_simple", 6, 4087126, "anatomicalEntity"),
(104, "calls/expr_calls/Pan_troglodytes_expr_simple_development.tsv.gz", "Pan_troglodytes_expr_simple_development.tsv.gz", "expr_simple", 6, 7748105, "anatomicalEntity,developmentalStage"),
(105, "calls/expr_calls/Rattus_norvegicus_expr_advanced.tsv.gz", "Rattus_norvegicus_expr_advanced.tsv.gz", "expr_complete", 10, 4607362, "anatomicalEntity"),
(106, "calls/expr_calls/Rattus_norvegicus_expr_advanced_development.tsv.gz", "Rattus_norvegicus_expr_advanced_development.tsv.gz", "expr_complete", 10, 5791363, "anatomicalEntity,developmentalStage"),
(107, "calls/expr_calls/Rattus_norvegicus_expr_simple.tsv.gz", "Rattus_norvegicus_expr_simple.tsv.gz", "expr_simple", 10, 3705081, "anatomicalEntity"),
(108, "calls/expr_calls/Rattus_norvegicus_expr_simple_development.tsv.gz", "Rattus_norvegicus_expr_simple_development.tsv.gz", "expr_simple", 10, 4893792, "anatomicalEntity,developmentalStage"),
(109, "calls/expr_calls/Sus_scrofa_expr_advanced.tsv.gz", "Sus_scrofa_expr_advanced.tsv.gz", "expr_complete", 12, 9666704, "anatomicalEntity"),
(110, "calls/expr_calls/Sus_scrofa_expr_advanced_development.tsv.gz", "Sus_scrofa_expr_advanced_development.tsv.gz", "expr_complete", 12, 13733277, "anatomicalEntity,developmentalStage"),
(111, "calls/expr_calls/Sus_scrofa_expr_simple.tsv.gz", "Sus_scrofa_expr_simple.tsv.gz", "expr_simple", 12, 7653613, "anatomicalEntity"),
(112, "calls/expr_calls/Sus_scrofa_expr_simple_development.tsv.gz", "Sus_scrofa_expr_simple_development.tsv.gz", "expr_simple", 12, 7653613, "anatomicalEntity,developmentalStage"),
(113, "calls/expr_calls/Xenopus_tropicalis_expr_advanced.tsv.gz", "Xenopus_tropicalis_expr_advanced.tsv.gz", "expr_complete", 23, 1941942, "anatomicalEntity"),
(114, "calls/expr_calls/Xenopus_tropicalis_expr_advanced_development.tsv.gz", "Xenopus_tropicalis_expr_advanced_development.tsv.gz", "expr_complete", 23, 8592883, "anatomicalEntity,developmentalStage"),
(115, "calls/expr_calls/Xenopus_tropicalis_expr_simple.tsv.gz", "Xenopus_tropicalis_expr_simple.tsv.gz", "expr_simple", 23, 1504455, "anatomicalEntity"),
(116, "calls/expr_calls/Xenopus_tropicalis_expr_simple_development.tsv.gz", "Xenopus_tropicalis_expr_simple_development.tsv.gz", "expr_simple", 23, 7204744, "anatomicalEntity,developmentalStage"),
(117, "processed_expr_values/affymetrix/Caenorhabditis_elegans/Caenorhabditis_elegans_Affymetrix_experiments_chips.tar.gz", "Caenorhabditis_elegans_Affymetrix_experiments_chips.tar.gz", "affy_annot", 5, 14216, NULL),
(118, "processed_expr_values/affymetrix/Caenorhabditis_elegans/Caenorhabditis_elegans_Affymetrix_probesets.tar.gz", "Caenorhabditis_elegans_Affymetrix_probesets.tar.gz", "affy_data", 5, 36240790, NULL),
(119, "processed_expr_values/affymetrix/Danio_rerio/Danio_rerio_Affymetrix_experiments_chips.tar.gz", "Danio_rerio_Affymetrix_experiments_chips.tar.gz", "affy_annot", 3, 22547, NULL),
(120, "processed_expr_values/affymetrix/Danio_rerio/Danio_rerio_Affymetrix_probesets.tar.gz", "Danio_rerio_Affymetrix_probesets.tar.gz", "affy_data", 3, 23625166, NULL),
(121, "processed_expr_values/affymetrix/Drosophila_melanogaster/Drosophila_melanogaster_Affymetrix_experiments_chips.tar.gz", "Drosophila_melanogaster_Affymetrix_experiments_chips.tar.gz", "affy_annot", 4, 71523, NULL),
(122, "processed_expr_values/affymetrix/Drosophila_melanogaster/Drosophila_melanogaster_Affymetrix_probesets.tar.gz", "Drosophila_melanogaster_Affymetrix_probesets.tar.gz", "affy_data", 4, 131009362, NULL),
(123, "processed_expr_values/affymetrix/Homo_sapiens/Homo_sapiens_Affymetrix_experiments_chips.tar.gz", "Homo_sapiens_Affymetrix_experiments_chips.tar.gz", "affy_annot", 1, 317769, NULL),
(124, "processed_expr_values/affymetrix/Homo_sapiens/Homo_sapiens_Affymetrix_probesets.tar.gz", "Homo_sapiens_Affymetrix_probesets.tar.gz", "affy_data", 1, 1653373277, NULL),
(125, "processed_expr_values/affymetrix/Macaca_mulatta/Macaca_mulatta_Affymetrix_experiments_chips.tar.gz", "Macaca_mulatta_Affymetrix_experiments_chips.tar.gz", "affy_annot", 9, 2004, NULL),
(126, "processed_expr_values/affymetrix/Macaca_mulatta/Macaca_mulatta_Affymetrix_probesets.tar.gz", "Macaca_mulatta_Affymetrix_probesets.tar.gz", "affy_data", 9, 3543010, NULL),
(127, "processed_expr_values/affymetrix/Mus_musculus/Mus_musculus_Affymetrix_experiments_chips.tar.gz", "Mus_musculus_Affymetrix_experiments_chips.tar.gz", "affy_annot", 2, 512832, NULL),
(128, "processed_expr_values/affymetrix/Mus_musculus/Mus_musculus_Affymetrix_probesets.tar.gz", "Mus_musculus_Affymetrix_probesets.tar.gz", "affy_data", 2, 1461785969, NULL),
(129, "processed_expr_values/affymetrix/Rattus_norvegicus/Rattus_norvegicus_Affymetrix_experiments_chips.tar.gz", "Rattus_norvegicus_Affymetrix_experiments_chips.tar.gz", "affy_annot", 10, 5299, NULL),
(130, "processed_expr_values/affymetrix/Rattus_norvegicus/Rattus_norvegicus_Affymetrix_probesets.tar.gz", "Rattus_norvegicus_Affymetrix_probesets.tar.gz", "affy_data", 10, 11199868, NULL),
(131, "processed_expr_values/rna_seq/Anolis_carolinensis/Anolis_carolinensis_RNA-Seq_experiments_libraries.tar.gz", "Anolis_carolinensis_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 22, 4252, NULL),
(132, "processed_expr_values/rna_seq/Anolis_carolinensis/Anolis_carolinensis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Anolis_carolinensis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 22, 9957222, NULL),
(133, "processed_expr_values/rna_seq/Bos_taurus/Bos_taurus_RNA-Seq_experiments_libraries.tar.gz", "Bos_taurus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 11, 83533, NULL),
(134, "processed_expr_values/rna_seq/Bos_taurus/Bos_taurus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Bos_taurus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 11, 244671496, NULL),
(135, "processed_expr_values/rna_seq/Caenorhabditis_elegans/Caenorhabditis_elegans_RNA-Seq_experiments_libraries.tar.gz", "Caenorhabditis_elegans_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 5, 4339, NULL),
(136, "processed_expr_values/rna_seq/Caenorhabditis_elegans/Caenorhabditis_elegans_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Caenorhabditis_elegans_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 5, 19590373, NULL),
(137, "processed_expr_values/rna_seq/Canis_lupus_familiaris/Canis_lupus_familiaris_RNA-Seq_experiments_libraries.tar.gz", "Canis_lupus_familiaris_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 15, 17139, NULL),
(138, "processed_expr_values/rna_seq/Canis_lupus_familiaris/Canis_lupus_familiaris_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Canis_lupus_familiaris_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 15, 57345010, NULL),
(139, "processed_expr_values/rna_seq/Cavia_porcellus/Cavia_porcellus_RNA-Seq_experiments_libraries.tar.gz", "Cavia_porcellus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 17, 17377, NULL),
(140, "processed_expr_values/rna_seq/Cavia_porcellus/Cavia_porcellus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Cavia_porcellus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 17, 87397125, NULL),
(141, "processed_expr_values/rna_seq/Danio_rerio/Danio_rerio_RNA-Seq_experiments_libraries.tar.gz", "Danio_rerio_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 3, 13868, NULL),
(142, "processed_expr_values/rna_seq/Danio_rerio/Danio_rerio_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Danio_rerio_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 3, 71223342, NULL),
(143, "processed_expr_values/rna_seq/Drosophila_ananassae/Drosophila_ananassae_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_ananassae_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 24, 1051, NULL),
(144, "processed_expr_values/rna_seq/Drosophila_ananassae/Drosophila_ananassae_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_ananassae_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 24, 1048421, NULL),
(145, "processed_expr_values/rna_seq/Drosophila_melanogaster/Drosophila_melanogaster_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_melanogaster_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 4, 18270, NULL),
(146, "processed_expr_values/rna_seq/Drosophila_melanogaster/Drosophila_melanogaster_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_melanogaster_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 4, 67895026, NULL),
(147, "processed_expr_values/rna_seq/Drosophila_mojavensis/Drosophila_mojavensis_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_mojavensis_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 25, 1370, NULL),
(148, "processed_expr_values/rna_seq/Drosophila_mojavensis/Drosophila_mojavensis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_mojavensis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 25, 2085332, NULL),
(149, "processed_expr_values/rna_seq/Drosophila_pseudoobscura/Drosophila_pseudoobscura_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_pseudoobscura_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 26, 1541, NULL),
(150, "processed_expr_values/rna_seq/Drosophila_pseudoobscura/Drosophila_pseudoobscura_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_pseudoobscura_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 26, 2773389, NULL),
(151, "processed_expr_values/rna_seq/Drosophila_simulans/Drosophila_simulans_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_simulans_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 27, 2264, NULL),
(152, "processed_expr_values/rna_seq/Drosophila_simulans/Drosophila_simulans_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_simulans_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 27, 3837574, NULL),
(153, "processed_expr_values/rna_seq/Drosophila_virilis/Drosophila_virilis_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_virilis_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 28, 1052, NULL),
(154, "processed_expr_values/rna_seq/Drosophila_virilis/Drosophila_virilis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_virilis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 28, 1046502, NULL),
(155, "processed_expr_values/rna_seq/Drosophila_yakuba/Drosophila_yakuba_RNA-Seq_experiments_libraries.tar.gz", "Drosophila_yakuba_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 29, 1048, NULL),
(156, "processed_expr_values/rna_seq/Drosophila_yakuba/Drosophila_yakuba_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Drosophila_yakuba_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 29, 1135479, NULL),
(157, "processed_expr_values/rna_seq/Equus_caballus/Equus_caballus_RNA-Seq_experiments_libraries.tar.gz", "Equus_caballus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 13, 24606, NULL),
(158, "processed_expr_values/rna_seq/Equus_caballus/Equus_caballus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Equus_caballus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 13, 81548401, NULL),
(159, "processed_expr_values/rna_seq/Erinaceus_europaeus/Erinaceus_europaeus_RNA-Seq_experiments_libraries.tar.gz", "Erinaceus_europaeus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 18, 1161, NULL),
(160, "processed_expr_values/rna_seq/Erinaceus_europaeus/Erinaceus_europaeus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Erinaceus_europaeus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 18, 1704833, NULL),
(161, "processed_expr_values/rna_seq/Felis_catus/Felis_catus_RNA-Seq_experiments_libraries.tar.gz", "Felis_catus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 16, 4872, NULL),
(162, "processed_expr_values/rna_seq/Felis_catus/Felis_catus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Felis_catus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 16, 11331917, NULL),
(163, "processed_expr_values/rna_seq/Gallus_gallus/Gallus_gallus_RNA-Seq_experiments_libraries.tar.gz", "Gallus_gallus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 21, 5963, NULL),
(164, "processed_expr_values/rna_seq/Gallus_gallus/Gallus_gallus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Gallus_gallus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 21, 13094112, NULL),
(165, "processed_expr_values/rna_seq/Gorilla_gorilla/Gorilla_gorilla_RNA-Seq_experiments_libraries.tar.gz", "Gorilla_gorilla_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 8, 3047, NULL),
(166, "processed_expr_values/rna_seq/Gorilla_gorilla/Gorilla_gorilla_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Gorilla_gorilla_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 8, 5900144, NULL),
(167, "processed_expr_values/rna_seq/Homo_sapiens/Homo_sapiens_RNA-Seq_experiments_libraries.tar.gz", "Homo_sapiens_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 1, 315991, NULL),
(168, "processed_expr_values/rna_seq/Homo_sapiens/Homo_sapiens_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Homo_sapiens_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 1, 4231127013, NULL),
(169, "processed_expr_values/rna_seq/Macaca_mulatta/Macaca_mulatta_RNA-Seq_experiments_libraries.tar.gz", "Macaca_mulatta_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 9, 21195, NULL),
(170, "processed_expr_values/rna_seq/Macaca_mulatta/Macaca_mulatta_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Macaca_mulatta_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 9, 94949248, NULL),
(171, "processed_expr_values/rna_seq/Monodelphis_domestica/Monodelphis_domestica_RNA-Seq_experiments_libraries.tar.gz", "Monodelphis_domestica_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 19, 13074, NULL),
(172, "processed_expr_values/rna_seq/Monodelphis_domestica/Monodelphis_domestica_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Monodelphis_domestica_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 19, 40013886, NULL),
(173, "processed_expr_values/rna_seq/Mus_musculus/Mus_musculus_RNA-Seq_experiments_libraries.tar.gz", "Mus_musculus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 2, 39989, NULL),
(174, "processed_expr_values/rna_seq/Mus_musculus/Mus_musculus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Mus_musculus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 2, 273012975, NULL),
(175, "processed_expr_values/rna_seq/Ornithorhynchus_anatinus/Ornithorhynchus_anatinus_RNA-Seq_experiments_libraries.tar.gz", "Ornithorhynchus_anatinus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 20, 4522, NULL),
(176, "processed_expr_values/rna_seq/Ornithorhynchus_anatinus/Ornithorhynchus_anatinus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Ornithorhynchus_anatinus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 20, 7608414, NULL),
(177, "processed_expr_values/rna_seq/Oryctolagus_cuniculus/Oryctolagus_cuniculus_RNA-Seq_experiments_libraries.tar.gz", "Oryctolagus_cuniculus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 14, 10551, NULL),
(178, "processed_expr_values/rna_seq/Oryctolagus_cuniculus/Oryctolagus_cuniculus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Oryctolagus_cuniculus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 14, 33310574, NULL),
(179, "processed_expr_values/rna_seq/Pan_paniscus/Pan_paniscus_RNA-Seq_experiments_libraries.tar.gz", "Pan_paniscus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 7, 2639, NULL),
(180, "processed_expr_values/rna_seq/Pan_paniscus/Pan_paniscus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Pan_paniscus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 7, 4595221, NULL),
(181, "processed_expr_values/rna_seq/Pan_troglodytes/Pan_troglodytes_RNA-Seq_experiments_libraries.tar.gz", "Pan_troglodytes_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 6, 20688, NULL),
(182, "processed_expr_values/rna_seq/Pan_troglodytes/Pan_troglodytes_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Pan_troglodytes_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 6, 84047916, NULL),
(183, "processed_expr_values/rna_seq/Rattus_norvegicus/Rattus_norvegicus_RNA-Seq_experiments_libraries.tar.gz", "Rattus_norvegicus_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 10, 10408, NULL),
(184, "processed_expr_values/rna_seq/Rattus_norvegicus/Rattus_norvegicus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Rattus_norvegicus_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 10, 45744961, NULL),
(185, "processed_expr_values/rna_seq/Sus_scrofa/Sus_scrofa_RNA-Seq_experiments_libraries.tar.gz", "Sus_scrofa_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 12, 36647, NULL),
(186, "processed_expr_values/rna_seq/Sus_scrofa/Sus_scrofa_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Sus_scrofa_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 12, 151366771, NULL),
(187, "processed_expr_values/rna_seq/Xenopus_tropicalis/Xenopus_tropicalis_RNA-Seq_experiments_libraries.tar.gz", "Xenopus_tropicalis_RNA-Seq_experiments_libraries.tar.gz", "rnaseq_annot", 23, 16055, NULL),
(188, "processed_expr_values/rna_seq/Xenopus_tropicalis/Xenopus_tropicalis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "Xenopus_tropicalis_RNA-Seq_read_counts_TPM_FPKM.tar.gz", "rnaseq_data", 23, 77786583, NULL);
