-- TODO enable multispecies groups when necessary
-- TODO fix insertion of download files

-- query to get the single species data groups for easier generation of this file:
SELECT speciesDisplayOrder,
        IF(speciesCommonName IS NOT NULL AND speciesCommonName != '',
           speciesCommonName, CONCAT(genus, ' ', species)),
        speciesDisplayOrder
FROM species ORDER BY speciesDisplayOrder;

-- query to get member of a given taxon, to help build the multi-species groups
SELECT t3.* from taxon as t1 inner join taxon as t2 
    ON t2.taxonLeftBound >= t1.taxonLeftBound
    AND t2.taxonRightBound <= t1.taxonRightBound
INNER JOIN species AS t3 on t3.taxonId = t2.taxonId
WHERE t1.taxonId = 1437010;



INSERT INTO speciesDataGroup (speciesDataGroupId, speciesDataGroupName, speciesDataGroupDescription,
speciesDataGroupOrder) VALUES
-- single-species data groups
(1, 'human', NULL, 1),
(2, 'mouse', NULL, 2),
(3, 'zebrafish', NULL, 3),
(4, 'fruit fly', NULL, 4),
(5, 'nematode', NULL, 5),
(6, 'chimpanzee', NULL, 6),
(7, 'bonobo', NULL, 7),
(8, 'gorilla', NULL, 8),
(9, 'macaque', NULL, 9),
(10, 'rat', NULL, 10),
(11, 'cattle', NULL, 11),
(12, 'pig', NULL, 12),
(13, 'horse', NULL, 13),
(14, 'rabbit', NULL, 14),
(15, 'dog', NULL, 15),
(16, 'cat', NULL, 16),
(17, 'guinea pig', NULL, 17),
(18, 'hedgehog', NULL, 18),
(19, 'opossum', NULL, 19),
(20, 'platypus', NULL, 20),
(21, 'chicken', NULL, 21),
(22, 'green anole', NULL, 22),
(23, 'western clawed frog', NULL, 23),
(24, 'Drosophila ananassae', NULL, 24),
(25, 'Drosophila mojavensis', NULL, 25),
(26, 'Drosophila pseudoobscura', NULL, 26),
(27, 'Drosophila simulans', NULL, 27),
(28, 'Drosophila virilis', NULL, 28),
(29, 'Drosophila yakuba', NULL, 29),

-- multi-species data group
--(30, 'human/mouse', NULL, 30),
--(31, 'Primates', NULL, 31),
--(32, 'Rodentia', NULL, 32),
--(33, 'Theria', NULL, 33),
--(34, 'Mammalia', NULL, 34),
--(35, 'Amniota', NULL, 35),
--(36, 'Tetrapoda', NULL, 36),
--(37, 'Teleostomi', NULL, 37),
--
--(39, 'Drosophila (genus)', NULL, 38),
-- worm + drosophila
--(40, 'Ecdysozoa', NULL, 39),
--
-- hedgehog, dog, cat, horse, pig, cattle
--(38, 'Laurasiatheria', NULL, 40),
--(41, 'Livestock', NULL, 41),
--(42, 'Domestic animals', NULL, 42);


INSERT INTO speciesToDataGroup (speciesDataGroupId, speciesId) VALUES 
-- single-species data groups
(1, 9606),
(2, 10090),
(3, 7955),
(4, 7227),
(5, 6239),
(6, 9598),
(7, 9597),
(8, 9593),
(9, 9544),
(10, 10116),
(11, 9913),
(12, 9823),
(13, 9796),
(14, 9986),
(15, 9615),
(16, 9685),
(17, 10141),
(18, 9365),
(19, 13616),
(20, 9258),
(21, 9031),
(22, 28377),
(23, 8364),
(24, 7217),
(25, 7230),
(26, 7237),
(27, 7240),
(28, 7244),
(29, 7245),

-- multi-species data groups
--(30, 9606),
--(30, 10090),
--
--(31, 9606),
--(31, 9598),
--(31, 9597),
--(31, 9593),
--(31, 9544),
--
--(32, 10090),
--(32, 10116),
--(32, 10141),
--
--(33, 9606),
--(33, 10090),
--(33, 9598),
--(33, 9597),
--(33, 9593),
--(33, 9544),
--(33, 10116),
--(33, 9913),
--(33, 9823),
--(33, 9796),
--(33, 9986),
--(33, 9615),
--(33, 9685),
--(33, 10141),
--(33, 9365),
--(33, 13616),
--
--(34, 9606),
--(34, 10090),
--(34, 9598),
--(34, 9597),
--(34, 9593),
--(34, 9544),
--(34, 10116),
--(34, 9913),
--(34, 9823),
--(34, 9796),
--(34, 9986),
--(34, 9615),
--(34, 9685),
--(34, 10141),
--(34, 9365),
--(34, 13616),
--(34, 9258),
--
--(35, 9606),
--(35, 10090),
--(35, 9598),
--(35, 9597),
--(35, 9593),
--(35, 9544),
--(35, 10116),
--(35, 9913),
--(35, 9823),
--(35, 9796),
--(35, 9986),
--(35, 9615),
--(35, 9685),
--(35, 10141),
--(35, 9365),
--(35, 13616),
--(35, 9258),
--(35, 9031),
--(35, 28377),
--
--(36, 9606),
--(36, 10090),
--(36, 9598),
--(36, 9597),
--(36, 9593),
--(36, 9544),
--(36, 10116),
--(36, 9913),
--(36, 9823),
--(36, 9796),
--(36, 9986),
--(36, 9615),
--(36, 9685),
--(36, 10141),
--(36, 9365),
--(36, 13616),
--(36, 9258),
--(36, 9031),
--(36, 28377),
--(36, 8364),
--
--(37, 9606),
--(37, 10090),
--(37, 9598),
--(37, 9597),
--(37, 9593),
--(37, 9544),
--(37, 10116),
--(37, 9913),
--(37, 9823),
--(37, 9796),
--(37, 9986),
--(37, 9615),
--(37, 9685),
--(37, 10141),
--(37, 9365),
--(37, 13616),
--(37, 9258),
--(37, 9031),
--(37, 28377),
--(37, 8364),
--(37, 7955),
--
--(38, 9913),
--(38, 9823),
--(38, 9796),
--(38, 9615),
--(38, 9685),
--(38, 9365),
--
--(39, 7227),
--(39, 7217),
--(39, 7230),
--(39, 7237),
--(39, 7240),
--(39, 7244),
--(39, 7245),
--
--(40, 7227),
--(40, 7217),
--(40, 7230),
--(40, 7237),
--(40, 7240),
--(40, 7244),
--(40, 7245),
--(40, 6239),
--
--(41, 9823),
--(41, 9913),
--
--(42, 9031),
--(42, 9615),
--(42, 9685),
--(42, 9796),
--(42, 9823),
--(42, 9913),
--(42, 9986),
--(42, 10141);

INSERT INTO downloadFile (downloadFileId, downloadFileRelativePath, downloadFileName, downloadFileCategory, speciesDataGroupId, downloadFileSize, downloadFileConditionParameters)
VALUES (1, "calls/expr_calls/Anolis_carolinensis_expr_advanced.tsv.zip", "Anolis_carolinensis_expr_advanced.tsv.zip", "expr_complete", 22, 524797, "anatomicalEntity"),
(2, "calls/expr_calls/Anolis_carolinensis_expr_advanced_development.tsv.zip", "Anolis_carolinensis_expr_advanced_development.tsv.zip", "expr_complete", 22, 528622, "anatomicalEntity,developmentalStage"),
(3, "calls/expr_calls/Anolis_carolinensis_expr_simple.tsv.zip", "Anolis_carolinensis_expr_simple.tsv.zip", "expr_simple", 22, 471004, "anatomicalEntity"),
(4, "calls/expr_calls/Anolis_carolinensis_expr_simple_development.tsv.zip", "Anolis_carolinensis_expr_simple_development.tsv.zip", "expr_simple", 22, 498791, "anatomicalEntity,developmentalStage"),
(5, "calls/expr_calls/Bos_taurus_expr_advanced.tsv.zip", "Bos_taurus_expr_advanced.tsv.zip", "expr_complete", 11, 1543500, "anatomicalEntity"),
(6, "calls/expr_calls/Bos_taurus_expr_advanced_development.tsv.zip", "Bos_taurus_expr_advanced_development.tsv.zip", "expr_complete", 11, 1572848, "anatomicalEntity,developmentalStage"),
(7, "calls/expr_calls/Bos_taurus_expr_simple.tsv.zip", "Bos_taurus_expr_simple.tsv.zip", "expr_simple", 11, 1308976, "anatomicalEntity"),
(8, "calls/expr_calls/Bos_taurus_expr_simple_development.tsv.zip", "Bos_taurus_expr_simple_development.tsv.zip", "expr_simple", 11, 1386692, "anatomicalEntity,developmentalStage"),
(9, "calls/expr_calls/Caenorhabditis_elegans_expr_advanced.tsv.zip", "Caenorhabditis_elegans_expr_advanced.tsv.zip", "expr_complete", 5, 1136046, "anatomicalEntity"),
(10, "calls/expr_calls/Caenorhabditis_elegans_expr_advanced_development.tsv.zip", "Caenorhabditis_elegans_expr_advanced_development.tsv.zip", "expr_complete", 5, 5674680, "anatomicalEntity,developmentalStage"),
(11, "calls/expr_calls/Caenorhabditis_elegans_expr_simple.tsv.zip", "Caenorhabditis_elegans_expr_simple.tsv.zip", "expr_simple", 5, 912401, "anatomicalEntity"),
(12, "calls/expr_calls/Caenorhabditis_elegans_expr_simple_development.tsv.zip", "Caenorhabditis_elegans_expr_simple_development.tsv.zip", "expr_simple", 5, 4864683, "anatomicalEntity,developmentalStage"),
(13, "calls/expr_calls/Canis_lupus_familiaris_expr_advanced.tsv.zip", "Canis_lupus_familiaris_expr_advanced.tsv.zip", "expr_complete", 15, 453029, "anatomicalEntity"),
(14, "calls/expr_calls/Canis_lupus_familiaris_expr_advanced_development.tsv.zip", "Canis_lupus_familiaris_expr_advanced_development.tsv.zip", "expr_complete", 15, 455616, "anatomicalEntity,developmentalStage"),
(15, "calls/expr_calls/Canis_lupus_familiaris_expr_simple.tsv.zip", "Canis_lupus_familiaris_expr_simple.tsv.zip", "expr_simple", 15, 411420, "anatomicalEntity"),
(16, "calls/expr_calls/Canis_lupus_familiaris_expr_simple_development.tsv.zip", "Canis_lupus_familiaris_expr_simple_development.tsv.zip", "expr_simple", 15, 427559, "anatomicalEntity,developmentalStage"),
(17, "calls/expr_calls/Cavia_porcellus_expr_advanced.tsv.zip", "Cavia_porcellus_expr_advanced.tsv.zip", "expr_complete", 17, 426594, "anatomicalEntity"),
(18, "calls/expr_calls/Cavia_porcellus_expr_advanced_development.tsv.zip", "Cavia_porcellus_expr_advanced_development.tsv.zip", "expr_complete", 17, 436669, "anatomicalEntity,developmentalStage"),
(19, "calls/expr_calls/Cavia_porcellus_expr_simple.tsv.zip", "Cavia_porcellus_expr_simple.tsv.zip", "expr_simple", 17, 384865, "anatomicalEntity"),
(20, "calls/expr_calls/Cavia_porcellus_expr_simple_development.tsv.zip", "Cavia_porcellus_expr_simple_development.tsv.zip", "expr_simple", 17, 402805, "anatomicalEntity,developmentalStage"),
(21, "calls/expr_calls/Danio_rerio_expr_advanced.tsv.zip", "Danio_rerio_expr_advanced.tsv.zip", "expr_complete", 3, 6979842, "anatomicalEntity"),
(22, "calls/expr_calls/Danio_rerio_expr_advanced_development.tsv.zip", "Danio_rerio_expr_advanced_development.tsv.zip", "expr_complete", 3, 12836200, "anatomicalEntity,developmentalStage"),
(23, "calls/expr_calls/Danio_rerio_expr_simple.tsv.zip", "Danio_rerio_expr_simple.tsv.zip", "expr_simple", 3, 5134188, "anatomicalEntity"),
(24, "calls/expr_calls/Danio_rerio_expr_simple_development.tsv.zip", "Danio_rerio_expr_simple_development.tsv.zip", "expr_simple", 3, 9853853, "anatomicalEntity,developmentalStage"),
(25, "calls/expr_calls/Drosophila_ananassae_expr_advanced.tsv.zip", "Drosophila_ananassae_expr_advanced.tsv.zip", "expr_complete", 24, 120749, "anatomicalEntity"),
(26, "calls/expr_calls/Drosophila_ananassae_expr_advanced_development.tsv.zip", "Drosophila_ananassae_expr_advanced_development.tsv.zip", "expr_complete", 24, 120735, "anatomicalEntity,developmentalStage"),
(27, "calls/expr_calls/Drosophila_ananassae_expr_simple.tsv.zip", "Drosophila_ananassae_expr_simple.tsv.zip", "expr_simple", 24, 112231, "anatomicalEntity"),
(28, "calls/expr_calls/Drosophila_ananassae_expr_simple_development.tsv.zip", "Drosophila_ananassae_expr_simple_development.tsv.zip", "expr_simple", 24, 116213, "anatomicalEntity,developmentalStage"),
(29, "calls/expr_calls/Drosophila_melanogaster_expr_advanced.tsv.zip", "Drosophila_melanogaster_expr_advanced.tsv.zip", "expr_complete", 4, 4736198, "anatomicalEntity"),
(30, "calls/expr_calls/Drosophila_melanogaster_expr_advanced_development.tsv.zip", "Drosophila_melanogaster_expr_advanced_development.tsv.zip", "expr_complete", 4, 8958296, "anatomicalEntity,developmentalStage"),
(31, "calls/expr_calls/Drosophila_melanogaster_expr_simple.tsv.zip", "Drosophila_melanogaster_expr_simple.tsv.zip", "expr_simple", 4, 3311233, "anatomicalEntity"),
(32, "calls/expr_calls/Drosophila_melanogaster_expr_simple_development.tsv.zip", "Drosophila_melanogaster_expr_simple_development.tsv.zip", "expr_simple", 4, 6733921, "anatomicalEntity,developmentalStage"),
(33, "calls/expr_calls/Drosophila_mojavensis_expr_advanced.tsv.zip", "Drosophila_mojavensis_expr_advanced.tsv.zip", "expr_complete", 25, 211763, "anatomicalEntity"),
(34, "calls/expr_calls/Drosophila_mojavensis_expr_advanced_development.tsv.zip", "Drosophila_mojavensis_expr_advanced_development.tsv.zip", "expr_complete", 25, 212970, "anatomicalEntity,developmentalStage"),
(35, "calls/expr_calls/Drosophila_mojavensis_expr_simple.tsv.zip", "Drosophila_mojavensis_expr_simple.tsv.zip", "expr_simple", 25, 192432, "anatomicalEntity"),
(36, "calls/expr_calls/Drosophila_mojavensis_expr_simple_development.tsv.zip", "Drosophila_mojavensis_expr_simple_development.tsv.zip", "expr_simple", 25, 207335, "anatomicalEntity,developmentalStage"),
(37, "calls/expr_calls/Drosophila_pseudoobscura_expr_advanced.tsv.zip", "Drosophila_pseudoobscura_expr_advanced.tsv.zip", "expr_complete", 26, 536817, "anatomicalEntity"),
(38, "calls/expr_calls/Drosophila_pseudoobscura_expr_advanced_development.tsv.zip", "Drosophila_pseudoobscura_expr_advanced_development.tsv.zip", "expr_complete", 26, 541032, "anatomicalEntity,developmentalStage"),
(39, "calls/expr_calls/Drosophila_pseudoobscura_expr_simple.tsv.zip", "Drosophila_pseudoobscura_expr_simple.tsv.zip", "expr_simple", 26, 486459, "anatomicalEntity"),
(40, "calls/expr_calls/Drosophila_pseudoobscura_expr_simple_development.tsv.zip", "Drosophila_pseudoobscura_expr_simple_development.tsv.zip", "expr_simple", 26, 515649, "anatomicalEntity,developmentalStage"),
(41, "calls/expr_calls/Drosophila_simulans_expr_advanced.tsv.zip", "Drosophila_simulans_expr_advanced.tsv.zip", "expr_complete", 27, 430409, "anatomicalEntity"),
(42, "calls/expr_calls/Drosophila_simulans_expr_advanced_development.tsv.zip", "Drosophila_simulans_expr_advanced_development.tsv.zip", "expr_complete", 27, 421683, "anatomicalEntity,developmentalStage"),
(43, "calls/expr_calls/Drosophila_simulans_expr_simple.tsv.zip", "Drosophila_simulans_expr_simple.tsv.zip", "expr_simple", 27, 391685, "anatomicalEntity"),
(44, "calls/expr_calls/Drosophila_simulans_expr_simple_development.tsv.zip", "Drosophila_simulans_expr_simple_development.tsv.zip", "expr_simple", 27, 406913, "anatomicalEntity,developmentalStage"),
(45, "calls/expr_calls/Drosophila_virilis_expr_advanced.tsv.zip", "Drosophila_virilis_expr_advanced.tsv.zip", "expr_complete", 28, 118579, "anatomicalEntity"),
(46, "calls/expr_calls/Drosophila_virilis_expr_advanced_development.tsv.zip", "Drosophila_virilis_expr_advanced_development.tsv.zip", "expr_complete", 28, 118536, "anatomicalEntity,developmentalStage"),
(47, "calls/expr_calls/Drosophila_virilis_expr_simple.tsv.zip", "Drosophila_virilis_expr_simple.tsv.zip", "expr_simple", 28, 110323, "anatomicalEntity"),
(48, "calls/expr_calls/Drosophila_virilis_expr_simple_development.tsv.zip", "Drosophila_virilis_expr_simple_development.tsv.zip", "expr_simple", 28, 114075, "anatomicalEntity,developmentalStage"),
(49, "calls/expr_calls/Drosophila_yakuba_expr_advanced.tsv.zip", "Drosophila_yakuba_expr_advanced.tsv.zip", "expr_complete", 29, 132640, "anatomicalEntity"),
(50, "calls/expr_calls/Drosophila_yakuba_expr_advanced_development.tsv.zip", "Drosophila_yakuba_expr_advanced_development.tsv.zip", "expr_complete", 29, 132251, "anatomicalEntity,developmentalStage"),
(51, "calls/expr_calls/Drosophila_yakuba_expr_simple.tsv.zip", "Drosophila_yakuba_expr_simple.tsv.zip", "expr_simple", 29, 123641, "anatomicalEntity"),
(52, "calls/expr_calls/Drosophila_yakuba_expr_simple_development.tsv.zip", "Drosophila_yakuba_expr_simple_development.tsv.zip", "expr_simple", 29, 127805, "anatomicalEntity,developmentalStage"),
(53, "calls/expr_calls/Equus_caballus_expr_advanced.tsv.zip", "Equus_caballus_expr_advanced.tsv.zip", "expr_complete", 13, 470260, "anatomicalEntity"),
(54, "calls/expr_calls/Equus_caballus_expr_advanced_development.tsv.zip", "Equus_caballus_expr_advanced_development.tsv.zip", "expr_complete", 13, 472085, "anatomicalEntity,developmentalStage"),
(55, "calls/expr_calls/Equus_caballus_expr_simple.tsv.zip", "Equus_caballus_expr_simple.tsv.zip", "expr_simple", 13, 425821, "anatomicalEntity"),
(56, "calls/expr_calls/Equus_caballus_expr_simple_development.tsv.zip", "Equus_caballus_expr_simple_development.tsv.zip", "expr_simple", 13, 442280, "anatomicalEntity,developmentalStage"),
(57, "calls/expr_calls/Erinaceus_europaeus_expr_advanced.tsv.zip", "Erinaceus_europaeus_expr_advanced.tsv.zip", "expr_complete", 18, 383903, "anatomicalEntity"),
(58, "calls/expr_calls/Erinaceus_europaeus_expr_advanced_development.tsv.zip", "Erinaceus_europaeus_expr_advanced_development.tsv.zip", "expr_complete", 18, 385530, "anatomicalEntity,developmentalStage"),
(59, "calls/expr_calls/Erinaceus_europaeus_expr_simple.tsv.zip", "Erinaceus_europaeus_expr_simple.tsv.zip", "expr_simple", 18, 347982, "anatomicalEntity"),
(60, "calls/expr_calls/Erinaceus_europaeus_expr_simple_development.tsv.zip", "Erinaceus_europaeus_expr_simple_development.tsv.zip", "expr_simple", 18, 362034, "anatomicalEntity,developmentalStage"),
(61, "calls/expr_calls/Felis_catus_expr_advanced.tsv.zip", "Felis_catus_expr_advanced.tsv.zip", "expr_complete", 16, 445493, "anatomicalEntity"),
(62, "calls/expr_calls/Felis_catus_expr_advanced_development.tsv.zip", "Felis_catus_expr_advanced_development.tsv.zip", "expr_complete", 16, 447848, "anatomicalEntity,developmentalStage"),
(63, "calls/expr_calls/Felis_catus_expr_simple.tsv.zip", "Felis_catus_expr_simple.tsv.zip", "expr_simple", 16, 405063, "anatomicalEntity"),
(64, "calls/expr_calls/Felis_catus_expr_simple_development.tsv.zip", "Felis_catus_expr_simple_development.tsv.zip", "expr_simple", 16, 420922, "anatomicalEntity,developmentalStage"),
(65, "calls/expr_calls/Gallus_gallus_expr_advanced.tsv.zip", "Gallus_gallus_expr_advanced.tsv.zip", "expr_complete", 21, 1368054, "anatomicalEntity"),
(66, "calls/expr_calls/Gallus_gallus_expr_advanced_development.tsv.zip", "Gallus_gallus_expr_advanced_development.tsv.zip", "expr_complete", 21, 1968985, "anatomicalEntity,developmentalStage"),
(67, "calls/expr_calls/Gallus_gallus_expr_simple.tsv.zip", "Gallus_gallus_expr_simple.tsv.zip", "expr_simple", 21, 1106728, "anatomicalEntity"),
(68, "calls/expr_calls/Gallus_gallus_expr_simple_development.tsv.zip", "Gallus_gallus_expr_simple_development.tsv.zip", "expr_simple", 21, 1707056, "anatomicalEntity,developmentalStage"),
(69, "calls/expr_calls/Gorilla_gorilla_expr_advanced.tsv.zip", "Gorilla_gorilla_expr_advanced.tsv.zip", "expr_complete", 8, 1250203, "anatomicalEntity"),
(70, "calls/expr_calls/Gorilla_gorilla_expr_advanced_development.tsv.zip", "Gorilla_gorilla_expr_advanced_development.tsv.zip", "expr_complete", 8, 1270880, "anatomicalEntity,developmentalStage"),
(71, "calls/expr_calls/Gorilla_gorilla_expr_simple.tsv.zip", "Gorilla_gorilla_expr_simple.tsv.zip", "expr_simple", 8, 1054040, "anatomicalEntity"),
(72, "calls/expr_calls/Gorilla_gorilla_expr_simple_development.tsv.zip", "Gorilla_gorilla_expr_simple_development.tsv.zip", "expr_simple", 8, 1108880, "anatomicalEntity,developmentalStage"),
(73, "calls/expr_calls/Homo_sapiens_expr_advanced.tsv.zip", "Homo_sapiens_expr_advanced.tsv.zip", "expr_complete", 1, 115656731, "anatomicalEntity"),
(74, "calls/expr_calls/Homo_sapiens_expr_advanced_development.tsv.zip", "Homo_sapiens_expr_advanced_development.tsv.zip", "expr_complete", 1, 365002964, "anatomicalEntity,developmentalStage"),
(75, "calls/expr_calls/Homo_sapiens_expr_simple.tsv.zip", "Homo_sapiens_expr_simple.tsv.zip", "expr_simple", 1, 63916590, "anatomicalEntity"),
(76, "calls/expr_calls/Homo_sapiens_expr_simple_development.tsv.zip", "Homo_sapiens_expr_simple_development.tsv.zip", "expr_simple", 1, 307718276, "anatomicalEntity,developmentalStage"),
(77, "calls/expr_calls/Macaca_mulatta_expr_advanced.tsv.zip", "Macaca_mulatta_expr_advanced.tsv.zip", "expr_complete", 9, 2931588, "anatomicalEntity"),
(78, "calls/expr_calls/Macaca_mulatta_expr_advanced_development.tsv.zip", "Macaca_mulatta_expr_advanced_development.tsv.zip", "expr_complete", 9, 2978770, "anatomicalEntity,developmentalStage"),
(79, "calls/expr_calls/Macaca_mulatta_expr_simple.tsv.zip", "Macaca_mulatta_expr_simple.tsv.zip", "expr_simple", 9, 2403168, "anatomicalEntity"),
(80, "calls/expr_calls/Macaca_mulatta_expr_simple_development.tsv.zip", "Macaca_mulatta_expr_simple_development.tsv.zip", "expr_simple", 9, 2535840, "anatomicalEntity,developmentalStage"),
(81, "calls/expr_calls/Monodelphis_domestica_expr_advanced.tsv.zip", "Monodelphis_domestica_expr_advanced.tsv.zip", "expr_complete", 19, 1224994, "anatomicalEntity"),
(82, "calls/expr_calls/Monodelphis_domestica_expr_advanced_development.tsv.zip", "Monodelphis_domestica_expr_advanced_development.tsv.zip", "expr_complete", 19, 1947015, "anatomicalEntity,developmentalStage"),
(83, "calls/expr_calls/Monodelphis_domestica_expr_simple.tsv.zip", "Monodelphis_domestica_expr_simple.tsv.zip", "expr_simple", 19, 1033279, "anatomicalEntity"),
(84, "calls/expr_calls/Monodelphis_domestica_expr_simple_development.tsv.zip", "Monodelphis_domestica_expr_simple_development.tsv.zip", "expr_simple", 19, 1711437, "anatomicalEntity,developmentalStage"),
(85, "calls/expr_calls/Mus_musculus_expr_advanced.tsv.zip", "Mus_musculus_expr_advanced.tsv.zip", "expr_complete", 2, 102120337, "anatomicalEntity"),
(86, "calls/expr_calls/Mus_musculus_expr_advanced_development.tsv.zip", "Mus_musculus_expr_advanced_development.tsv.zip", "expr_complete", 2, 206990631, "anatomicalEntity,developmentalStage"),
(87, "calls/expr_calls/Mus_musculus_expr_simple.tsv.zip", "Mus_musculus_expr_simple.tsv.zip", "expr_simple", 2, 50679942, "anatomicalEntity"),
(88, "calls/expr_calls/Mus_musculus_expr_simple_development.tsv.zip", "Mus_musculus_expr_simple_development.tsv.zip", "expr_simple", 2, 169035639, "anatomicalEntity,developmentalStage"),
(89, "calls/expr_calls/Ornithorhynchus_anatinus_expr_advanced.tsv.zip", "Ornithorhynchus_anatinus_expr_advanced.tsv.zip", "expr_complete", 20, 1138816, "anatomicalEntity"),
(90, "calls/expr_calls/Ornithorhynchus_anatinus_expr_advanced_development.tsv.zip", "Ornithorhynchus_anatinus_expr_advanced_development.tsv.zip", "expr_complete", 20, 1148024, "anatomicalEntity,developmentalStage"),
(91, "calls/expr_calls/Ornithorhynchus_anatinus_expr_simple.tsv.zip", "Ornithorhynchus_anatinus_expr_simple.tsv.zip", "expr_simple", 20, 958772, "anatomicalEntity"),
(92, "calls/expr_calls/Ornithorhynchus_anatinus_expr_simple_development.tsv.zip", "Ornithorhynchus_anatinus_expr_simple_development.tsv.zip", "expr_simple", 20, 1016924, "anatomicalEntity,developmentalStage"),
(93, "calls/expr_calls/Oryctolagus_cuniculus_expr_advanced.tsv.zip", "Oryctolagus_cuniculus_expr_advanced.tsv.zip", "expr_complete", 14, 426191, "anatomicalEntity"),
(94, "calls/expr_calls/Oryctolagus_cuniculus_expr_advanced_development.tsv.zip", "Oryctolagus_cuniculus_expr_advanced_development.tsv.zip", "expr_complete", 14, 428339, "anatomicalEntity,developmentalStage"),
(95, "calls/expr_calls/Oryctolagus_cuniculus_expr_simple.tsv.zip", "Oryctolagus_cuniculus_expr_simple.tsv.zip", "expr_simple", 14, 386772, "anatomicalEntity"),
(96, "calls/expr_calls/Oryctolagus_cuniculus_expr_simple_development.tsv.zip", "Oryctolagus_cuniculus_expr_simple_development.tsv.zip", "expr_simple", 14, 401521, "anatomicalEntity,developmentalStage"),
(97, "calls/expr_calls/Pan_paniscus_expr_advanced.tsv.zip", "Pan_paniscus_expr_advanced.tsv.zip", "expr_complete", 7, 937266, "anatomicalEntity"),
(98, "calls/expr_calls/Pan_paniscus_expr_advanced_development.tsv.zip", "Pan_paniscus_expr_advanced_development.tsv.zip", "expr_complete", 7, 1666521, "anatomicalEntity,developmentalStage"),
(99, "calls/expr_calls/Pan_paniscus_expr_simple.tsv.zip", "Pan_paniscus_expr_simple.tsv.zip", "expr_simple", 7, 840220, "anatomicalEntity"),
(100, "calls/expr_calls/Pan_paniscus_expr_simple_development.tsv.zip", "Pan_paniscus_expr_simple_development.tsv.zip", "expr_simple", 7, 1506175, "anatomicalEntity,developmentalStage"),
(101, "calls/expr_calls/Pan_troglodytes_expr_advanced.tsv.zip", "Pan_troglodytes_expr_advanced.tsv.zip", "expr_complete", 6, 955354, "anatomicalEntity"),
(102, "calls/expr_calls/Pan_troglodytes_expr_advanced_development.tsv.zip", "Pan_troglodytes_expr_advanced_development.tsv.zip", "expr_complete", 6, 1852275, "anatomicalEntity,developmentalStage"),
(103, "calls/expr_calls/Pan_troglodytes_expr_simple.tsv.zip", "Pan_troglodytes_expr_simple.tsv.zip", "expr_simple", 6, 854896, "anatomicalEntity"),
(104, "calls/expr_calls/Pan_troglodytes_expr_simple_development.tsv.zip", "Pan_troglodytes_expr_simple_development.tsv.zip", "expr_simple", 6, 1673251, "anatomicalEntity,developmentalStage"),
(105, "calls/expr_calls/Rattus_norvegicus_expr_advanced.tsv.zip", "Rattus_norvegicus_expr_advanced.tsv.zip", "expr_complete", 10, 1962001, "anatomicalEntity"),
(106, "calls/expr_calls/Rattus_norvegicus_expr_advanced_development.tsv.zip", "Rattus_norvegicus_expr_advanced_development.tsv.zip", "expr_complete", 10, 2064493, "anatomicalEntity,developmentalStage"),
(107, "calls/expr_calls/Rattus_norvegicus_expr_simple.tsv.zip", "Rattus_norvegicus_expr_simple.tsv.zip", "expr_simple", 10, 1644265, "anatomicalEntity"),
(108, "calls/expr_calls/Rattus_norvegicus_expr_simple_development.tsv.zip", "Rattus_norvegicus_expr_simple_development.tsv.zip", "expr_simple", 10, 1811515, "anatomicalEntity,developmentalStage"),
(109, "calls/expr_calls/Sus_scrofa_expr_advanced.tsv.zip", "Sus_scrofa_expr_advanced.tsv.zip", "expr_complete", 12, 923968, "anatomicalEntity"),
(110, "calls/expr_calls/Sus_scrofa_expr_advanced_development.tsv.zip", "Sus_scrofa_expr_advanced_development.tsv.zip", "expr_complete", 12, 1081599, "anatomicalEntity,developmentalStage"),
(111, "calls/expr_calls/Sus_scrofa_expr_simple.tsv.zip", "Sus_scrofa_expr_simple.tsv.zip", "expr_simple", 12, 785760, "anatomicalEntity"),
(112, "calls/expr_calls/Sus_scrofa_expr_simple_development.tsv.zip", "Sus_scrofa_expr_simple_development.tsv.zip", "expr_simple", 12, 943931, "anatomicalEntity,developmentalStage"),
(113, "calls/expr_calls/Xenopus_tropicalis_expr_advanced.tsv.zip", "Xenopus_tropicalis_expr_advanced.tsv.zip", "expr_complete", 23, 1879337, "anatomicalEntity"),
(114, "calls/expr_calls/Xenopus_tropicalis_expr_advanced_development.tsv.zip", "Xenopus_tropicalis_expr_advanced_development.tsv.zip", "expr_complete", 23, 4144604, "anatomicalEntity,developmentalStage"),
(115, "calls/expr_calls/Xenopus_tropicalis_expr_simple.tsv.zip", "Xenopus_tropicalis_expr_simple.tsv.zip", "expr_simple", 23, 1484731, "anatomicalEntity"),
(116, "calls/expr_calls/Xenopus_tropicalis_expr_simple_development.tsv.zip", "Xenopus_tropicalis_expr_simple_development.tsv.zip", "expr_simple", 23, 3481281, "anatomicalEntity,developmentalStage"),
(117, "processed_expr_values/affymetrix/Caenorhabditis_elegans/Caenorhabditis_elegans_Affymetrix_experiments_chips.zip", "Caenorhabditis_elegans_Affymetrix_experiments_chips.zip", "affy_annot", 5, 14229, "null"),
(118, "processed_expr_values/affymetrix/Caenorhabditis_elegans/Caenorhabditis_elegans_Affymetrix_probesets.zip", "Caenorhabditis_elegans_Affymetrix_probesets.zip", "affy_data", 5, 36368956, "null"),
(119, "processed_expr_values/affymetrix/Danio_rerio/Danio_rerio_Affymetrix_experiments_chips.zip", "Danio_rerio_Affymetrix_experiments_chips.zip", "affy_annot", 3, 22411, "null"),
(120, "processed_expr_values/affymetrix/Danio_rerio/Danio_rerio_Affymetrix_probesets.zip", "Danio_rerio_Affymetrix_probesets.zip", "affy_data", 3, 23687059, "null"),
(121, "processed_expr_values/affymetrix/Drosophila_melanogaster/Drosophila_melanogaster_Affymetrix_experiments_chips.zip", "Drosophila_melanogaster_Affymetrix_experiments_chips.zip", "affy_annot", 4, 70183, "null"),
(122, "processed_expr_values/affymetrix/Drosophila_melanogaster/Drosophila_melanogaster_Affymetrix_probesets.zip", "Drosophila_melanogaster_Affymetrix_probesets.zip", "affy_data", 4, 131097521, "null"),
(123, "processed_expr_values/affymetrix/Homo_sapiens/Homo_sapiens_Affymetrix_experiments_chips.zip", "Homo_sapiens_Affymetrix_experiments_chips.zip", "affy_annot", 1, 316932, "null"),
(124, "processed_expr_values/affymetrix/Homo_sapiens/Homo_sapiens_Affymetrix_probesets.zip", "Homo_sapiens_Affymetrix_probesets.zip", "affy_data", 1, 1650268803, "null"),
(125, "processed_expr_values/affymetrix/Macaca_mulatta/Macaca_mulatta_Affymetrix_experiments_chips.zip", "Macaca_mulatta_Affymetrix_experiments_chips.zip", "affy_annot", 9, 2344, "null"),
(126, "processed_expr_values/affymetrix/Macaca_mulatta/Macaca_mulatta_Affymetrix_probesets.zip", "Macaca_mulatta_Affymetrix_probesets.zip", "affy_data", 9, 3522346, "null"),
(127, "processed_expr_values/affymetrix/Mus_musculus/Mus_musculus_Affymetrix_experiments_chips.zip", "Mus_musculus_Affymetrix_experiments_chips.zip", "affy_annot", 2, 512372, "null"),
(128, "processed_expr_values/affymetrix/Mus_musculus/Mus_musculus_Affymetrix_probesets.zip", "Mus_musculus_Affymetrix_probesets.zip", "affy_data", 2, 1463603537, "null"),
(129, "processed_expr_values/affymetrix/Rattus_norvegicus/Rattus_norvegicus_Affymetrix_experiments_chips.zip", "Rattus_norvegicus_Affymetrix_experiments_chips.zip", "affy_annot", 10, 5537, "null"),
(130, "processed_expr_values/affymetrix/Rattus_norvegicus/Rattus_norvegicus_Affymetrix_probesets.zip", "Rattus_norvegicus_Affymetrix_probesets.zip", "affy_data", 10, 11213396, "null"),
(131, "processed_expr_values/rna_seq/Anolis_carolinensis/Anolis_carolinensis_RNA-Seq_experiments_libraries.zip", "Anolis_carolinensis_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 22, 1903, "null"),
(132, "processed_expr_values/rna_seq/Anolis_carolinensis/Anolis_carolinensis_RNA-Seq_read_counts_TPM_FPKM.zip", "Anolis_carolinensis_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 22, 6498163, "null"),
(133, "processed_expr_values/rna_seq/Bos_taurus/Bos_taurus_RNA-Seq_experiments_libraries.zip", "Bos_taurus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 11, 3414, "null"),
(134, "processed_expr_values/rna_seq/Bos_taurus/Bos_taurus_RNA-Seq_read_counts_TPM_FPKM.zip", "Bos_taurus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 11, 71556473, "null"),
(135, "processed_expr_values/rna_seq/Caenorhabditis_elegans/Caenorhabditis_elegans_RNA-Seq_experiments_libraries.zip", "Caenorhabditis_elegans_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 5, 5192, "null"),
(136, "processed_expr_values/rna_seq/Caenorhabditis_elegans/Caenorhabditis_elegans_RNA-Seq_read_counts_TPM_FPKM.zip", "Caenorhabditis_elegans_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 5, 21597488, "null"),
(137, "processed_expr_values/rna_seq/Canis_lupus_familiaris/Canis_lupus_familiaris_RNA-Seq_experiments_libraries.zip", "Canis_lupus_familiaris_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 15, 1544, "null"),
(138, "processed_expr_values/rna_seq/Canis_lupus_familiaris/Canis_lupus_familiaris_RNA-Seq_read_counts_TPM_FPKM.zip", "Canis_lupus_familiaris_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 15, 24428993, "null"),
(139, "processed_expr_values/rna_seq/Cavia_porcellus/Cavia_porcellus_RNA-Seq_experiments_libraries.zip", "Cavia_porcellus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 17, 1634, "null"),
(140, "processed_expr_values/rna_seq/Cavia_porcellus/Cavia_porcellus_RNA-Seq_read_counts_TPM_FPKM.zip", "Cavia_porcellus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 17, 24428976, "null"),
(141, "processed_expr_values/rna_seq/Danio_rerio/Danio_rerio_RNA-Seq_experiments_libraries.zip", "Danio_rerio_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 3, 7011, "null"),
(142, "processed_expr_values/rna_seq/Danio_rerio/Danio_rerio_RNA-Seq_read_counts_TPM_FPKM.zip", "Danio_rerio_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 3, 36877675, "null"),
(143, "processed_expr_values/rna_seq/Drosophila_ananassae/Drosophila_ananassae_RNA-Seq_experiments_libraries.zip", "Drosophila_ananassae_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 24, 1417, "null"),
(144, "processed_expr_values/rna_seq/Drosophila_ananassae/Drosophila_ananassae_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_ananassae_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 24, 14937880, "null"),
(145, "processed_expr_values/rna_seq/Drosophila_melanogaster/Drosophila_melanogaster_RNA-Seq_experiments_libraries.zip", "Drosophila_melanogaster_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 4, 2495, "null"),
(146, "processed_expr_values/rna_seq/Drosophila_melanogaster/Drosophila_melanogaster_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_melanogaster_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 4, 16468601, "null"),
(147, "processed_expr_values/rna_seq/Drosophila_mojavensis/Drosophila_mojavensis_RNA-Seq_experiments_libraries.zip", "Drosophila_mojavensis_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 25, 1723, "null"),
(148, "processed_expr_values/rna_seq/Drosophila_mojavensis/Drosophila_mojavensis_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_mojavensis_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 25, 14937892, "null"),
(149, "processed_expr_values/rna_seq/Drosophila_pseudoobscura/Drosophila_pseudoobscura_RNA-Seq_experiments_libraries.zip", "Drosophila_pseudoobscura_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 26, 2110, "null"),
(150, "processed_expr_values/rna_seq/Drosophila_pseudoobscura/Drosophila_pseudoobscura_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_pseudoobscura_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 26, 14937904, "null"),
(151, "processed_expr_values/rna_seq/Drosophila_simulans/Drosophila_simulans_RNA-Seq_experiments_libraries.zip", "Drosophila_simulans_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 27, 2097, "null"),
(152, "processed_expr_values/rna_seq/Drosophila_simulans/Drosophila_simulans_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_simulans_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 27, 14937878, "null"),
(153, "processed_expr_values/rna_seq/Drosophila_virilis/Drosophila_virilis_RNA-Seq_experiments_libraries.zip", "Drosophila_virilis_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 28, 1409, "null"),
(154, "processed_expr_values/rna_seq/Drosophila_virilis/Drosophila_virilis_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_virilis_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 28, 14937872, "null"),
(155, "processed_expr_values/rna_seq/Drosophila_yakuba/Drosophila_yakuba_RNA-Seq_experiments_libraries.zip", "Drosophila_yakuba_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 29, 1401, "null"),
(156, "processed_expr_values/rna_seq/Drosophila_yakuba/Drosophila_yakuba_RNA-Seq_read_counts_TPM_FPKM.zip", "Drosophila_yakuba_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 29, 14937871, "null"),
(157, "processed_expr_values/rna_seq/Equus_caballus/Equus_caballus_RNA-Seq_experiments_libraries.zip", "Equus_caballus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 13, 1601, "null"),
(158, "processed_expr_values/rna_seq/Equus_caballus/Equus_caballus_RNA-Seq_read_counts_TPM_FPKM.zip", "Equus_caballus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 13, 24428973, "null"),
(159, "processed_expr_values/rna_seq/Erinaceus_europaeus/Erinaceus_europaeus_RNA-Seq_experiments_libraries.zip", "Erinaceus_europaeus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 18, 1529, "null"),
(160, "processed_expr_values/rna_seq/Erinaceus_europaeus/Erinaceus_europaeus_RNA-Seq_read_counts_TPM_FPKM.zip", "Erinaceus_europaeus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 18, 24428990, "null"),
(161, "processed_expr_values/rna_seq/Felis_catus/Felis_catus_RNA-Seq_experiments_libraries.zip", "Felis_catus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 16, 1623, "null"),
(162, "processed_expr_values/rna_seq/Felis_catus/Felis_catus_RNA-Seq_read_counts_TPM_FPKM.zip", "Felis_catus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 16, 24428959, "null"),
(163, "processed_expr_values/rna_seq/Gallus_gallus/Gallus_gallus_RNA-Seq_experiments_libraries.zip", "Gallus_gallus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 21, 5551, "null"),
(164, "processed_expr_values/rna_seq/Gallus_gallus/Gallus_gallus_RNA-Seq_read_counts_TPM_FPKM.zip", "Gallus_gallus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 21, 122564375, "null"),
(165, "processed_expr_values/rna_seq/Gorilla_gorilla/Gorilla_gorilla_RNA-Seq_experiments_libraries.zip", "Gorilla_gorilla_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 8, 2933, "null"),
(166, "processed_expr_values/rna_seq/Gorilla_gorilla/Gorilla_gorilla_RNA-Seq_read_counts_TPM_FPKM.zip", "Gorilla_gorilla_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 8, 68938761, "null"),
(167, "processed_expr_values/rna_seq/Homo_sapiens/Homo_sapiens_RNA-Seq_experiments_libraries.zip", "Homo_sapiens_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 1, 246843, "null"),
(168, "processed_expr_values/rna_seq/Homo_sapiens/Homo_sapiens_RNA-Seq_read_counts_TPM_FPKM.zip", "Homo_sapiens_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 1, 3196661031, "null"),
(169, "processed_expr_values/rna_seq/Macaca_mulatta/Macaca_mulatta_RNA-Seq_experiments_libraries.zip", "Macaca_mulatta_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 9, 7170, "null"),
(170, "processed_expr_values/rna_seq/Macaca_mulatta/Macaca_mulatta_RNA-Seq_read_counts_TPM_FPKM.zip", "Macaca_mulatta_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 9, 131194141, "null"),
(171, "processed_expr_values/rna_seq/Monodelphis_domestica/Monodelphis_domestica_RNA-Seq_experiments_libraries.zip", "Monodelphis_domestica_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 19, 3317, "null"),
(172, "processed_expr_values/rna_seq/Monodelphis_domestica/Monodelphis_domestica_RNA-Seq_read_counts_TPM_FPKM.zip", "Monodelphis_domestica_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 19, 68938845, "null"),
(173, "processed_expr_values/rna_seq/Mus_musculus/Mus_musculus_RNA-Seq_experiments_libraries.zip", "Mus_musculus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 2, 11188, "null"),
(174, "processed_expr_values/rna_seq/Mus_musculus/Mus_musculus_RNA-Seq_read_counts_TPM_FPKM.zip", "Mus_musculus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 2, 188792296, "null"),
(175, "processed_expr_values/rna_seq/Ornithorhynchus_anatinus/Ornithorhynchus_anatinus_RNA-Seq_experiments_libraries.zip", "Ornithorhynchus_anatinus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 20, 3165, "null"),
(176, "processed_expr_values/rna_seq/Ornithorhynchus_anatinus/Ornithorhynchus_anatinus_RNA-Seq_read_counts_TPM_FPKM.zip", "Ornithorhynchus_anatinus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 20, 68938861, "null"),
(177, "processed_expr_values/rna_seq/Oryctolagus_cuniculus/Oryctolagus_cuniculus_RNA-Seq_experiments_libraries.zip", "Oryctolagus_cuniculus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 14, 1545, "null"),
(178, "processed_expr_values/rna_seq/Oryctolagus_cuniculus/Oryctolagus_cuniculus_RNA-Seq_read_counts_TPM_FPKM.zip", "Oryctolagus_cuniculus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 14, 24428991, "null"),
(179, "processed_expr_values/rna_seq/Pan_paniscus/Pan_paniscus_RNA-Seq_experiments_libraries.zip", "Pan_paniscus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 7, 2396, "null"),
(180, "processed_expr_values/rna_seq/Pan_paniscus/Pan_paniscus_RNA-Seq_read_counts_TPM_FPKM.zip", "Pan_paniscus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 7, 47544761, "null"),
(181, "processed_expr_values/rna_seq/Pan_troglodytes/Pan_troglodytes_RNA-Seq_experiments_libraries.zip", "Pan_troglodytes_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 6, 2555, "null"),
(182, "processed_expr_values/rna_seq/Pan_troglodytes/Pan_troglodytes_RNA-Seq_read_counts_TPM_FPKM.zip", "Pan_troglodytes_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 6, 47544784, "null"),
(183, "processed_expr_values/rna_seq/Rattus_norvegicus/Rattus_norvegicus_RNA-Seq_experiments_libraries.zip", "Rattus_norvegicus_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 10, 3642, "null"),
(184, "processed_expr_values/rna_seq/Rattus_norvegicus/Rattus_norvegicus_RNA-Seq_read_counts_TPM_FPKM.zip", "Rattus_norvegicus_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 10, 71556494, "null"),
(185, "processed_expr_values/rna_seq/Sus_scrofa/Sus_scrofa_RNA-Seq_experiments_libraries.zip", "Sus_scrofa_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 12, 1878, "null"),
(186, "processed_expr_values/rna_seq/Sus_scrofa/Sus_scrofa_RNA-Seq_read_counts_TPM_FPKM.zip", "Sus_scrofa_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 12, 25718503, "null"),
(187, "processed_expr_values/rna_seq/Xenopus_tropicalis/Xenopus_tropicalis_RNA-Seq_experiments_libraries.zip", "Xenopus_tropicalis_RNA-Seq_experiments_libraries.zip", "rnaseq_annot", 23, 5819, "null"),
(188, "processed_expr_values/rna_seq/Xenopus_tropicalis/Xenopus_tropicalis_RNA-Seq_read_counts_TPM_FPKM.zip", "Xenopus_tropicalis_RNA-Seq_read_counts_TPM_FPKM.zip", "rnaseq_data", 23, 40849740, "null");